export const mockStats = {
  tournament: {
    name: 'Liga Profesional',
    slug: 'liga-profesional',
    category: {
      name: 'Argentina',
      slug: 'argentina',
      sport: { name: 'Football', slug: 'football', id: 1 },
      id: 48,
      flag: 'argentina',
      alpha2: 'AR',
    },
    uniqueTournament: {
      name: 'Liga Profesional de F\u00fatbol',
      slug: 'liga-profesional-de-futbol',
      primaryColorHex: '#0cbad8',
      secondaryColorHex: '#daa813',
      category: {
        name: 'Argentina',
        slug: 'argentina',
        sport: { name: 'Football', slug: 'football', id: 1 },
        id: 48,
        flag: 'argentina',
        alpha2: 'AR',
      },
      userCount: 61310,
      id: 155,
      country: {},
      hasEventPlayerStatistics: true,
      crowdsourcingEnabled: false,
      hasPerformanceGraphFeature: true,
      displayInverseHomeAwayTeams: false,
    },
    priority: 335,
    competitionType: 1,
    id: 68,
  },
  season: {
    name: 'Liga Profesional 2023',
    year: '2023',
    editor: false,
    seasonCoverageInfo: {},
    id: 47647,
  },
  roundInfo: { round: 21 },
  customId: 'hobsrob',
  status: { code: 6, description: '1st half', type: 'inprogress' },
  winnerCode: 0,
  venue: {
    city: { name: 'Rosario' },
    stadium: { name: 'Gigante de Arroyito', capacity: 41654 },
    id: 1329,
    country: { alpha2: 'AR', name: 'Argentina' },
  },
  referee: {
    name: 'Nicolas Lamolina',
    slug: 'nicolas-lamolina',
    yellowCards: 818,
    redCards: 32,
    yellowRedCards: 30,
    games: 147,
    sport: { name: 'Football', slug: 'football', id: 1 },
    id: 782794,
    country: { alpha2: 'AR', name: 'Argentina' },
  },
  homeTeam: {
    name: 'Rosario Central',
    slug: 'rosario-central',
    shortName: 'Rosario Central',
    gender: 'M',
    sport: { name: 'Football', slug: 'football', id: 1 },
    userCount: 12615,
    manager: {
      name: 'Miguel Angel Russo',
      slug: 'miguel-angel-russo',
      shortName: 'M. A. Russo',
      id: 53483,
      country: { alpha2: 'AR', name: 'Argentina' },
    },
    venue: {
      city: { name: 'Rosario' },
      stadium: { name: 'Gigante de Arroyito', capacity: 41654 },
      id: 1329,
      country: { alpha2: 'AR', name: 'Argentina' },
    },
    foundationDate: {},
    nameCode: 'ROS',
    disabled: false,
    national: false,
    type: 0,
    id: 3217,
    country: { alpha2: 'AR', name: 'Argentina' },
    subTeams: [],
    fullName: 'Rosario Central',
    teamColors: { primary: '#000066', secondary: '#ffcc00', text: '#ffcc00' },
    foundationDateTimestamp: -2525212800,
  },
  awayTeam: {
    name: 'Col\u00f3n',
    slug: 'colon',
    shortName: 'Col\u00f3n',
    gender: 'M',
    sport: { name: 'Football', slug: 'football', id: 1 },
    userCount: 10275,
    manager: {
      name: 'Nestor Gorosito',
      slug: 'nestor-gorosito',
      shortName: 'N. Gorosito',
      id: 784603,
      country: { alpha2: 'AR', name: 'Argentina' },
    },
    venue: {
      city: { name: 'Santa Fe de la Vera Cruz' },
      stadium: { name: 'Estadio Brigadier Estanislao Lopez', capacity: 40000 },
      id: 1566,
      country: { alpha2: 'AR', name: 'Argentina' },
    },
    foundationDate: {},
    nameCode: 'COL',
    disabled: false,
    national: false,
    type: 0,
    id: 3207,
    country: { alpha2: 'AR', name: 'Argentina' },
    subTeams: [],
    fullName: 'Col\u00f3n',
    teamColors: { primary: '#000000', secondary: '#cc0000', text: '#cc0000' },
    foundationDateTimestamp: -2040508800,
  },
  homeScore: { current: 0, display: 0 },
  awayScore: { current: 0, display: 0 },
  time: { initial: 0, max: 2700, extra: 540, currentPeriodStartTimestamp: 1687730460 },
  changes: { changes: ['time.currentPeriodStart'], changeTimestamp: 1687731806 },
  hasGlobalHighlights: false,
  hasEventPlayerStatistics: true,
  hasEventPlayerHeatMap: true,
  detailId: 1,
  crowdsourcingDataDisplayEnabled: false,
  id: 10981639,
  defaultPeriodCount: 2,
  defaultPeriodLength: 45,
  statusTime: { prefix: '', initial: 0, max: 2700, timestamp: 1687730460, extra: 540 },
  currentPeriodStartTimestamp: 1687730460,
  startTimestamp: 1687730400,
  slug: 'rosario-central-colon',
  lastPeriod: 'period1',
  finalResultOnly: false,
  hasBet365LiveStream: true,
  bet365ExcludedCountryCodes: ['AR', 'XA', 'XB', 'IR', 'GR', 'RU', 'CH', 'CA'],
  fanRatingEvent: false,
  seasonStatisticsType: 'overall',
  showTotoPromo: false,
}
