import type { PropsWithChildren } from 'react'
import { Inter, Josefin_Sans } from 'next/font/google'
import ReactQueryProvider from '@/app/ReactQueryProvider'
import '@/styles/globals.scss'

const inter = Inter({
  variable: '--font-inter',
  subsets: ['latin'],
})

const josefin = Josefin_Sans({
  variable: '--font-josefin',
  subsets: ['latin'],
})

export const metadata = {
  title: 'Score',
  description: 'Generated by score',
}

export default function RootLayout({ children }: PropsWithChildren) {
  return (
    <html lang='en'>
      <body className={inter.variable}>
        <ReactQueryProvider>{children}</ReactQueryProvider>
      </body>
    </html>
  )
}
